server:
  port: 9000
  
spring:
  application:
    name: zuul-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/springcloudconfig?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    leaseRenewalIntervalInSeconds: 3
    registry-fetch-interval-seconds: 3
zuul:
  retryable: true
